name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'actions/setup-python@v5'
      with:
        python-version: '3.12'
    - name: yamlllint
      run: |
        pip install yamllint==1.33.0
        yamllint module.yml
    - name: cfn-lint
      run: |
        pip install cfn-lint==0.85.0
        cfn-lint -t module.yml
    - name: license
      run: |
        grep -q "LICENSE-2.0" module.yml
